# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm install
      - name: Build
        env:
          AIRTABLE_AUTH_KEY: ${{ secrets.AIRTABLE_AUTH_KEY }}
          AIRTABLE_BASE_NAME: ${{ secrets.AIRTABLE_BASE_NAME }}
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './data'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          author_name: Villager Bot
          author_email: villager-bot@aoe4world.com
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: New content changes
